# Generated by Django 4.0.4 on 2022-06-13 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id_camera', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20, verbose_name='Местоположение камеры')),
                ('rtsp_address', models.CharField(max_length=50, verbose_name='RTSP адрес камеры')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('department', models.CharField(max_length=15, verbose_name='Отдел')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('position', models.CharField(max_length=15, verbose_name='Должность')),
                ('number_of_offenses', models.IntegerField(verbose_name='Количество нарушений')),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id_offense', models.AutoField(primary_key=True, serialize=False)),
                ('offense_date', models.DateField(default=datetime.date(2022, 6, 13), verbose_name='Дата нарушения')),
                ('offense_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время нарушения')),
                ('photo_offense', models.ImageField(upload_to='', verbose_name='Фотография нарушения')),
                ('id_camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.cameras')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees')),
            ],
        ),
    ]
