# Generated by Django 4.0.4 on 2022-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameras',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='offense',
            options={'verbose_name': 'Нарушение', 'verbose_name_plural': 'Нарушения'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
        migrations.RemoveField(
            model_name='offense',
            name='id_camera',
        ),
        migrations.AddField(
            model_name='offense',
            name='id_camera',
            field=models.ManyToManyField(to='main.cameras'),
        ),
    ]
