# Generated by Django 4.0.4 on 2022-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cameras_options_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offense',
            name='type_offense',
            field=models.CharField(default='В маске', max_length=15, verbose_name='Тип нарушения'),
        ),
    ]
