# Generated by Django 4.0.4 on 2022-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offense_type_offense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='type_offense',
            field=models.CharField(default='В маске', max_length=30, verbose_name='Тип нарушения'),
        ),
    ]
