# Generated by Django 4.0.4 on 2022-06-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_offense_type_offense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='main.employees'),
        ),
    ]
