# Generated by Django 4.0.4 on 2022-06-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_offense_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees'),
        ),
    ]
