# Generated by Django 4.0.4 on 2022-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_offense_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(upload_to='img/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='photo_offense',
            field=models.ImageField(upload_to='img/', verbose_name='Фотография нарушения'),
        ),
    ]
