# Generated by Django 4.0.4 on 2022-06-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employees_photo_alter_offense_photo_offense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='photo_offense',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Фотография нарушения'),
        ),
    ]
